export const MapIDToName={

    0: 'D-water Borderland',
    1: 'Map 1- AOL',
    2: 'Map 1- UOF',
    3: 'D1 Light portal',
    4: 'D1 Boss room',
    5: 'Cornwell',
    6: 'Light Asmo room',
    7: 'Agrilla',
    8: 'Knight room',
    9: 'D2',
    10: 'D2 level 2',
    11: 'Kimu room',
    12: 'Cloron',
    13: 'Cloron level 2',
    14: 'Cloron level 3',
    15: 'FL',
    16: 'FL level 2',
    17: 'FL level 3',
    18: 'Proelium',
    19: 'Light map2',
    20: 'Dark map2',
    21: 'Maitreyan',
    22: 'Maitreyan boss room',
    23: 'AidionNekria',
    24: 'AidionNekria floor2',
    25: 'Elemental Cave',
    26: 'RuberChaos',
    28: 'Light map3',
    29: 'dark map3',
    30: 'CANTA',
    31: '20-30 dungeon light',
    32: '20-30 dungeon dark',
    33: 'Fedion Temple',
    34: 'Kalamus House',
    35: 'Apulune',
    36: 'Iris',
    37: 'Stigma',
    38: 'AZ',
    39: 'SECRET battle arena',
    40: 'Arena',
    41: 'SECRET Prison',
    42: 'Auction House',
    43: 'Pando',
    44: 'Lanhaar',
    45: 'DD2',
    46: 'DD2',
    47: 'Jungle',
    48: 'CT',
    49: 'CT Level 2',
    50: 'GRB Map',
    51: 'Light Guildhouse',
    52: 'Dark Guildhouse',
    53: 'Light Managment Office',
    54: 'Dark Managment Office',
    55: 'SkyCity level 1',
    56: 'SkyCity level 2',
    57: 'SkyCity leve 3',
    58: 'SkyCity boss room',
    59: 'Fedion Temple',
    60: 'World Cup',
    61: 'Stigma',
    62: 'KH',
    63: 'AZ',
    64: 'Oblivion Insula',
    68: 'VR',
    69: 'PR',
    70: 'Kanos Illium',
    71: 'QV',
    72: 'QS',
    73: 'Zehar Mine',
    74: 'Dimension Crack',
    75: 'Fanta Screws',
    76: 'Theo Les',
    77: 'Dungeon Arcanus Ruins',
    78: 'Dungeon Arcanus Ruins 2F',
    79: 'Dungeon Hypnosis Ruins'

}
